### PR TITLE
skip files already downloaded

### PR DESCRIPTION
**Pull request by jconnor77**
skip files already downloaded

### CODE REVIEW

**Comment by llakssz** [comment]
thanks for making an account 👻 🎃 
and thanks for the contribution!

**Comment by llakssz** [comment]
so this will resume partially download files, and also skip them if they exist, very cool.

if you could add an argument (-overwrite), to make this feature optional, that would be perfect i think.

**Comment by abossard** [comment]
As far as I can see, it will not resume a download, but just redownload it (which is fine, I think)

**Comment by abossard** [comment]
it works, I checked it on my machine. I think it can be merged.

**Pull request merged**
