### PR TITLE
Add ability to download only EURO region instead of ALL

### PR DESCRIPTION
**Pull request by magicseb**
Use -eur tag instead of -all to download euro only games.

### CODE REVIEW

**Comment by llakssz** [comment]
Can you add 'all' 'jpn' 'usa' 'eur' too?

It is annoying that we cannot easily get the product code/serial - something like this for 3ds 'CTR-N-AKDJ'.
The last letter is the region of the content.

**Comment by abossard** [comment]
I like the idea, but I think it'd be better to provide the regions wanted as optional parameters to all, instead of -eur.

**Comment by llakssz** [comment]
a little bit how i did it here?:
https://github.com/llakssz/FunkyCIA/blob/master/FunkyCIA2.py#L83
use something like...
-region JPN EUR
-region USA

I'll take a look at the commits now.

**Comment by llakssz** [comment]
region is implemented now.

**Pull request closed without merging**
